# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cc2a9d384ea30446c8cc3f6420e0809585bb924a941be4f4800e7496cf52d7e8eca4fdf91f452244d4b1b23ad9cb2be02ab35d47aadb79d790252f049ccfc92

test:
  secret_key_base: aabd1da375b70145238aafaede6b489782f6137372b047634b9156382c9e0edc81508cda39ec20653c9aae7e41c8a1324e06d128cbcc6dc4af367d7fe1c3b07a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
